# Generated by Django 6.0.4 on 2026-04-14 19:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0002_question_submission_testcase'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProctorSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='proctor_frames/')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snapshots', to='tests.allowedcandidate')),
            ],
        ),
        migrations.CreateModel(
            name='Violation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('violation_type', models.CharField(choices=[('TAB_SWITCH', 'Tab Switched'), ('FOCUS_LOST', 'Browser Lost Focus'), ('DEV_TOOLS', 'Developer Tools Opened (F12)'), ('RIGHT_CLICK', 'Right Click Attempted'), ('COPY_PASTE', 'Copy/Paste Attempted')], max_length=20)),
                ('details', models.TextField(blank=True, help_text='Additional context if needed')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='violations', to='tests.allowedcandidate')),
            ],
        ),
    ]
