# Generated by Django 6.0.4 on 2026-04-14 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0003_proctorsnapshot_violation'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='is_final',
            field=models.BooleanField(default=False, help_text='True if this is the final submitted code'),
        ),
    ]
