# Generated by Django 6.0.4 on 2026-04-14 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0004_submission_is_final'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='image',
            field=models.ImageField(blank=True, help_text='Optional diagram or image for the question', null=True, upload_to='question_images/'),
        ),
    ]
