# Generated by Django 4.2.30 on 2026-04-15 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0005_question_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testcase',
            name='expected_output',
            field=models.TextField(blank=True, help_text='Expected standard output'),
        ),
    ]
