# Generated by Django 4.2.30 on 2026-04-18 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0006_alter_testcase_expected_output'),
    ]

    operations = [
        migrations.AddField(
            model_name='proctorsnapshot',
            name='cloud_url',
            field=models.URLField(blank=True, help_text='Permanent backup link on Cloudinary', null=True),
        ),
    ]
